#! /usr/bin/env ruby
#
echo 'hogehoge2'

require "pathname"
lib = Pathname.new(__FILE__).dirname.join("..", "lib").expand_path
$LOAD_PATH.unshift lib.to_s

require 'generate_schemafile'

GenerateSchemafile::Cli.start
