#! /usr/bin/env ruby

require "pathname"
lib = Pathname.new(__FILE__).dirname.join("..", "lib").expand_path
$LOAD_PATH.unshift lib.to_s

require 'optparse'
require 'generate_schemafile'

params = ARGV.getopts('', 'file_path:DB設計書.xlsm', 'output_path:Schemafile', 'help', 'require:')

GenerateSchemafile.invoke(params)
